apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-cdc
  namespace: dev-idra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-cdc
  template:
    metadata:
      labels:
        app: web-cdc
    spec:
      containers:
        - name: web-cdc
          image: 851725589037.dkr.ecr.eu-central-1.amazonaws.com/dev-cdc-rest-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ETCD
              value: "etcd:2379"
            - name: ETCD_USERNAME
              value: "root"
            - name: ETCD_PASSWORD
              value: "root"
            - name: DOMAIN
              value: "http://web-cdc-service.dev-idra.svc.cluster.local:8080"